### PR TITLE
Fixes issue causing failure with non-standard class/package names.

### LINKED ISSUE #25: Problem creating under a package with UpperCases
Hi,

I found this error this morning using it. 

# Reproduce Step:
- Create a package named MyPackage
- Create a autovalue ```MyPackage.MyAutoValue.class```
```java
@AutoValue public abstract class MyAutoValue {
    @SerializedName("test") public abstract String test();
    @SerializedName("test_2") public abstract String test2();

    public static MyAutoValue create() {
        return null;
    }
}
```
-> this compiles

- add the TypeAdapter
```java
@AutoValue public abstract class MyAutoValue {
    @SerializedName("test") public abstract String test();
    @SerializedName("test_2") public abstract String test2();

    public static MyAutoValue create() {
        return null;
    }

    public static TypeAdapter<MyAutoValue> typeAdapter(Gson gson) {
        return new AutoValue_TestAutoValueGson.GsonTypeAdapter(gson);
    }
}
```

```
Error:(8, 40) error: cannot find symbol class MyPackage
Error:(18, 78) error: package MyPackage does not exist
Error:(26, 59) error: package MyPackage does not exist
Error:(35, 25) error: package MyPackage does not exist
```

I had another error looking like this
Could not find best guess class for <fullpath>.MyPackage.MyAutoValue.class on line 144

```java
   ClassName autoValueClass = ClassName.bestGuess(context.autoValueClass().getQualifiedName().toString());
```

# How to avoid the problem using this release
Put all packages in lowercase

# ?
Does get qualified name is returning a path with lowercase and another package is looking to an uppercase path?

It was an error by my part using an uppercase in a package but I had hard time to pinpoint the problem.

I hope it helps

### PR DESCRIPTION
**Pull request by rharter**
Fixes #25

### CODE REVIEW

File: src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java [hunk 1]
```diff
@@ -433,4 +433,26 @@ public void simple() {
...
+        + "  public abstract String a();\n"
+        + "  public abstract boolean b();\n"
+        + "}"
+    );
+
+    assertAbout(javaSource())
+        .that(source1)
+        .processedWith(new AutoValueProcessor())
+        .compilesWithoutError()
+        .withWarningCount(2);
```
Comment (rharter) [inline src/test/java/com/ryanharter/auto/value/gson/AutoValueGsonExtensionTest.java]: Javac always throws two errors for AutoValue for unclaimed `@AutoValue` and `@Generated` dependencies.
