### PR TITLE
Fix factory method with generics

### LINKED ISSUE #226: Build failed in the generated read method for a generic class
https://github.com/rharter/auto-value-gson/blob/a1aa36ebcd3baf770840fc3c603f6db328e7ca24/auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java#L677
The line above will generate an error in the generated code for a generic class.
`error: <identifier> expected
      ObjectResponse.Builder builder = ObjectResponse<T>.<T>builder();`
```
    @Override
    @SuppressWarnings("unchecked")
    public ObjectResponse<T> read(JsonReader jsonReader) throws IOException {
      if (jsonReader.peek() == JsonToken.NULL) {
        jsonReader.nextNull();
        return null;
      }
      jsonReader.beginObject();
      ObjectResponse.Builder builder = ObjectResponse<T>.<T>builder(); // Build failed

      ...
```

version: 1.1.0

### PR DESCRIPTION
**Pull request by bryanstern**
Fixes #226.

Invalid java code was being generated when trying to instantiate a builder with generics via its factory method inside the `TypeAdapter#read`.

The fix is to use the builder's type rather than class when declaring the builder field inside of `TypeAdapter#read`.

I've also updated `GenericsExample` to show that it works and to serve as a test. The read method generated now looks like.

```java
public GenericsExample<A, B, C> read(JsonReader jsonReader) throws IOException {
  if (jsonReader.peek() == JsonToken.NULL) {
    jsonReader.nextNull();
    return null;
   }
   jsonReader.beginObject();
   GenericsExample.Builder<A, B, C> builder = GenericsExample.builder();
   ...
}
```

### CODE REVIEW

File: auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java [hunk 1]
```diff
@@ -589,7 +590,7 @@ private MethodSpec createReadMethod(ClassName className,
             .addMember("value", "\"unchecked\"")
             .build())
         .addModifiers(PUBLIC)
-        .returns(autoValueClassName)
+        .returns(autoValueTypeName)
```
Comment (bryanstern) [inline auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java]: This isn't functionally any different. Just a renamed variable.

File: auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java [hunk 2]
```diff
@@ -674,8 +675,8 @@ private MethodSpec createReadMethod(ClassName className,
           }
         }
 
-        readMethod.addStatement("$T $N = $T.$L", builderField.get().type, builderField.get(),
-            autoValueClassName, builderMethod);
+        readMethod.addStatement("$T $N = $T.$N()", builderField.get().type, builderField.get(),
+            autoValueClassName, builderMethod.getSimpleName());
```
Comment (bryanstern) [inline auto-value-gson/src/main/java/com/ryanharter/auto/value/gson/AutoValueGsonExtension.java]: `autoValueClassName` this is now a `ClassName` instance rather than a `TypeName` instance. We needed a `ClassName` instance otherwise this would have generated `Foo.Builder<T> builder = Foo<T>.builder();`
